wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712192466.0
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      - 79
      2:
      - 1
      - 41
      - 55
      - 71
      - 79
      3:
      - 17
      - 23
      - 37
      - 61
      4: 3.12.2
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
